### ISSUE TITLE
Session not defined?

### ISSUE THREAD

**Issue by flaviocarvalho** [elmarti/meteor-video-chat#4]
I got this error when Im about to make a call:
`ReferenceError: Session is not defined
    at _class.callRemote `
I've looked at your code and can't find the Session variable declaration

**Comment by flaviocarvalho** [comment]
meteor add session
add dependency

**Comment by elmarti** [comment]
Ah OK, in 1.2 Session was included as standard and they took it out in 1.3, I'll add it in as a dependecy ASAP

**Comment by flaviocarvalho** [comment]
Also, there I get an error when passing false to loadLocalWebcam, I got rid of it by adding some brackets on client.js line 107..
When I try to callRemote i get `insert failed: Callee is currently in a call`..

**Comment by elmarti** [comment]
It's because there's a clause which says that if the callee status is still in a call, then another one cannot be made to it. I'm hoping to make this a bit more dynamic in future, but I'm still exploring the options https://github.com/elmarti/meteor-video-chat/blob/master/services/server.js#L17 Are you calling callTerminated() when the call ends?

**Comment by elmarti** [comment]
There are a few ways in which I try to identify when the call should be automatically set to finished, such as when the user goes offline and is still in a call https://github.com/elmarti/meteor-video-chat/blob/master/services/server.js#L45

**Comment by elmarti** [comment]
I have just spotted an error in the observers, so i've pushed up an update of that.
