### ISSUE TITLE
Display video call on a new window browser

### ISSUE THREAD

**Issue by sir007** [elmarti/meteor-video-chat#61]
Hi elmarti,
great job! 

I'm building a video chat app using meteor-video-chat. All is ok with Modal (i'm still using version 0.4.13 ).
My aim is to display the video call in a new window browser (   with window.open() function ) like on facebook web video call system (it uses webrtc).

![fb 1-compressed](https://user-images.githubusercontent.com/19388696/34447299-cac31ed6-ece2-11e7-8833-41b9c51b055e.jpg)

I'm able to display the new window video call on the caller side; but not on the callee side.
Do you have any advise on how to do this?
Thanks.

**Comment by elmarti** [comment]
Hi @sir007, sounds great! I don't have time right now but I'll have a look into it when I can. I'm also going to put the link to the repo at that point in time https://github.com/elmarti/meteor-video-chat/tree/976136bf2eaa3ebddab51b0d105a04ee23c4068e

**Comment by elmarti** [comment]
I think I see the issue, it's due to the video chat extension being relatively dumb in how it identifies the user agents, at present it will simply send all of the data to all instances where the user is logged in, but it doesn't present a visible issue due to it ignoring the stream of WebRTC session data due to it not being initalised. This isn't something I've put a lot of thought into up until now, but it would be nice for this to work correctly, i'll do some testing on the current version as I've changed the data stream method from just using regular DDP to using Meteor's websockets directly.

The only thing I can suggest from looking at the old API is that calling 
```
    Meteor.VideoCallServices.loadLocalWebcam(false, function() {
        Meteor.VideoCallServices.answerCall()
    });
```
in the newly opened window should correctly initialize the session for that user agent, rather than the browser that it was opened from. Where are you calling that?

**Comment by sir007** [comment]
Thank's elmarti for your quick answer !

When the caller clicks on the video call button i replace the following code (Modal):
Modal.show("chatModal", {callee: Id, calleename: Name, isCaller: true}, {backdrop: 'static', keyboard: false});

with (New window):
window.open("http://localhost:3000/VideoCall?callee="+Id+"&calleename="+Name+"&isCaller="+true,
	"_blank", "width=800,height=800");

I also replace the following code (Modal):
Meteor.startup(function() {
    Meteor.VideoCallServices.onReceivePhoneCall = function() {
	  Modal.show("chatModal", {}, {backdrop: 'static'}); 
    }

with (New window):
Meteor.startup(function() {
    Meteor.VideoCallServices.onReceivePhoneCall = function() {
	  window.open("http://localhost:3000/VideoCall", "_blank", "width=800,height=800");
    }
I though that by replacing 	  Modal.show("chatModal", {}, {backdrop: 'static'});  with 	  window.open("http://localhost:3000/VideoCall", "_blank", "width=800,height=800");     i could display a new window call in the both sides; but the new window video call is only display on the caller side.
That is what i have done.

**Comment by elmarti** [comment]
Since adding connection specific sessions here https://github.com/elmarti/meteor-video-chat/issues/67, It should now be possible to do this, the trick would be calling 
```JavaScript 
VideoCallServices.answer({
    localElement: document.getElementById("localElement"),
    remoteElement: document.getElementById("remoteElement"),
    video:true, 
    audio:true
});
```` 
when the window.open is called, which will then lock it down to that browser instance and allow you to set the video elements etc
