### ISSUE TITLE
meteor-video-chat-example displays a blank page

### ISSUE THREAD

**Issue by sir007** [elmarti/meteor-video-chat#62]
Hi elmarti,
i'm currently testing meteor-video-chat 1.2.0 
I downloaded meteor-video-chat-example to test it in my local meteor installation. I'm surprised because i just have a blank page. I also notice that there is only a header page in the directory. 
In the version 0.4.13, there was a easy useful example.
Can you direct me on how to use this lastest version, in order to produce an app similar to the one you hosted on  https://meteorvideochat.herokuapp.com/ ?
Thanks

**Comment by elmarti** [comment]
Interesting, I will create an issue in that project and investigate it tomorrow

**Comment by elmarti** [comment]
https://github.com/elmarti/meteor-video-chat-example/issues/12

**Comment by elmarti** [comment]
It appears to be working fine on my local machine, as for the files, in order to make it easier to integrate ReactJS with SSR and to decouple it slightly, all files can be found in the "modules" folder. I did originally have plans to create example projects with all 3 client side libraries, but didn't out of lack of interest from users. If you like I can look at making one in Blaze.
