### ISSUE TITLE
[ERROR] Identifier Meteor has already been declared

### ISSUE THREAD

**Issue by jamalcoder** [elmarti/meteor-video-chat#86]
using meteor 1.7.0.5

after installing the package it throws this error (Identifier Meteor has already been declared)

**Comment by elmarti** [comment]
OK, I am able to reproduce this. I believe that this is due the the dependency injection pattern in which Meteor is indirectly referenced. (https://github.com/elmarti/meteor-video-chat/blob/681bf5601967c63170294b2a4d4764fe923d7284/lib/client.js#L71)

Is it working OK besides the error message? I'll have to look into why it's started logging that error, rather than trying to fix around it.

**Comment by elmarti** [comment]
I've opened an issue on the Meteor repo https://github.com/meteor/meteor/issues/10234

**Comment by aleritty** [comment]
For me no, it isn't working correctly.

It seems to me (but I can be wrong) an incompatibility with latest versions of meteor (1.7.x) because of different babel versions.

Actually if I use the atmosphere package I get this error and the package just doesn't work, but if I use the npm package with include, I get a "syntax error" and after that everything doesn't work (obviously).

To reproduce you can just "meteor update" your demo application (i tried with the blaze one)

**Comment by elmarti** [comment]
I have reproduced it, there seems to be a strange issue with how the module loading works in 1.7, it appears to be compiling multiple async modules into a single file which are each declared with `let`, which is what is causing the problem. Going to see if I can fix, but there seems to be a greater issue with the module scoping in packages for this release meteor/meteor#10234

**Comment by jamalcoder** [comment]
> Is it working OK besides the error message?

when installing the package(just installing without using it) my app works in dev mode but in production mode it fails 

just i want you to know that the last compatible version of (@babel/runtime) with meteor 1.7.0.x is 7.0.0-beta.55  maybe it's a babel issue as @aleritty says...but you can try the beta of meteor 1.7.1  it's compatible with tha last version of (@babel/runtime) and check if it's working

**Comment by elmarti** [comment]
@jamalcoder I've just posted a fix meteor-video-chat@2.3.1, it's definitely related to the bundling

**Comment by elmarti** [comment]
This has now been confirmed as a Meteor core bundling bug that will be fixed in 1.8. This package should still work with this fix and will stay the same unless any unseen issues arise
